#!/usr/bin/env python3
# made by me using smile as a template

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():
    
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    # get the most recent 50 tweets from screen name
    timeline = get_user_timeline(sys.argv[1], 50)
    if timeline is None:
        sys.exit("Timeline returned 'None' - username invalid")
    
    # send each tweet to analyser and calculate sentiment
    # then print score and tweet in appropriate colouring
    for tweet in timeline:
        score = analyzer.analyze(tweet)
        if score > 0.0:
            print(colored("{} {}".format(score, tweet), "green"))
        elif score < 0.0:
            print(colored("{} {}".format(score, tweet), "red"))
        else:
            print(colored("{} {}".format(score, tweet), "yellow"))

if __name__ == "__main__":
    main()
